# Generated by Django 4.1.7 on 2023-03-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.userdetails'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.userpreferences'),
        ),
    ]
