# Generated by Django 4.1.7 on 2023-04-17 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_match_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
