# Generated by Django 4.1.7 on 2023-04-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_match_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='in_match_pool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_survey',
            field=models.BooleanField(default=True),
        ),
    ]
