# Generated by Django 4.1.7 on 2023-04-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userpreferences_in_match_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='heuristic',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
    ]
