# Generated by Django 4.1.7 on 2023-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userdetails_heuristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='users',
        ),
        migrations.AddField(
            model_name='match',
            name='details_list',
            field=models.ManyToManyField(to='base.userdetails'),
        ),
        migrations.AddField(
            model_name='match',
            name='mean_agreeableness',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='mean_extroversion',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='mean_heuristic',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='mean_neuroticism',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='variance_agreeableness',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='variance_extroversion',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='variance_heuristic',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='variance_neuroticism',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
    ]
