# Generated by Django 4.1.7 on 2023-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_match_users_match_details_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_information_sheet',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='consent_participation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='consent_publication',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
