# Generated by Django 4.1.7 on 2023-04-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_consent_information_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consent_information_sheet',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_participation',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_publication',
            field=models.BooleanField(null=True),
        ),
    ]
