# Generated by Django 4.1.7 on 2023-04-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_consent_information_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='origin_date',
            field=models.DateField(auto_now=True),
        ),
    ]
