# Generated by Django 4.1.7 on 2023-04-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_match_origin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
