# Generated by Django 4.1.7 on 2023-05-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveydata',
            old_name='user',
            new_name='user_details',
        ),
        migrations.AddField(
            model_name='surveydata',
            name='concluding_additional',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Do you have any final thoughts or comments?'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='game_additional',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Do you have any other thoughts or opinions about the game?'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='game_affectiveness_accessible',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither agree nor disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None, null=True, verbose_name='The game is easily available / accessible <em>(2)</em>.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='game_affectiveness_approachable',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither agree nor disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None, null=True, verbose_name='The game is approachable <em>(1)</em>.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='game_affectiveness_interaction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither agree nor disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None, null=True, verbose_name='The game encouraged social interaction within your group.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='game_gamer',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not a gamer'), (2, 'Has played games'), (3, 'Casual gamer'), (4, 'Regular gamer'), (5, 'Hardcore gamer')], default=None, null=True, verbose_name='To what extent would you consider yourself a gamer?'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_additional',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Do you have any other thoughts or opinions regarding the group(s) you were matched with?'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_contact',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], default=None, max_length=1, null=True, verbose_name='Do you plan to keep in contact with anyone you met whilst participating?'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_relation_agreeable',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None of them'), (2, 'A few of them'), (3, 'About half'), (4, 'Most of them'), (5, 'All of them')], default=None, null=True, verbose_name='They were agreeable.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_relation_extroversion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None of them'), (2, 'A few of them'), (3, 'About half'), (4, 'Most of them'), (5, 'All of them')], default=None, null=True, verbose_name='They were extroverted.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_relation_introversion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None of them'), (2, 'A few of them'), (3, 'About half'), (4, 'Most of them'), (5, 'All of them')], default=None, null=True, verbose_name='They were introverted.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_relation_neuroticism',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None of them'), (2, 'A few of them'), (3, 'About half'), (4, 'Most of them'), (5, 'All of them')], default=None, null=True, verbose_name='They were emotionally stable.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='group_relation_overall',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None of them'), (2, 'A few of them'), (3, 'About half'), (4, 'Most of them'), (5, 'All of them')], default=None, null=True, verbose_name='You all got on well with each other.'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='social_isolation_before',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very socially isolated'), (2, 'Slightly socially isolated'), (3, 'Neither socially isolated or connected'), (4, 'Slightly socially connected'), (5, 'Very socially connected')], default=None, verbose_name='Before Participation'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='social_isolation_during',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very socially isolated'), (2, 'Slightly socially isolated'), (3, 'Neither socially isolated or connected'), (4, 'Slightly socially connected'), (5, 'Very socially connected')], default=None, verbose_name='During Participation'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='website_affectiveness_accessible',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True, verbose_name='To what extent does the website feel <em>accessible</em>?'),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='website_affectiveness_user_friendly',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True, verbose_name='To what extent does the website feel <em>user-friendly</em>?'),
        ),
    ]
